baseurl = "https://meifu.github.io/"
languageCode = "en-us"
title = "Meifu Kuo"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Meifu's Murmur"
	description = "murmuring..."

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "logo_old.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Meifu Kuo**,<br> a frontend Developer, <br>a music lover, and<br> a mom &hearts;."
		# The icons will be shown if you enter your username
		twitter = "meifu"
		github = "meifu"
		gitlab = "meifutoolate"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "meifukuo"

		copyright = [
			"&copy; Meifu Kuo",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Try to believe that I can do something."
		content = "After years of self-doubt, I guess I sholud start to do something. Even what I can do is so subtle... At least I can try to share my thoughts. Writing also can help me remember things better."


	[params.portfolio]
		hide  = false
		title = "Previous Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "design/artMusem.jpg"
			thumb = "design/artMusem.jpg"
			title = "Art Museum"
			description = "以前做的北美館提案，by photoshop"

		# [[params.portfolio.gallery]]
		#	image = "fulls/02.jpg"
		#	thumb = "thumbs/02.jpg"
		#	title = "Lorem ipsum dolor."
		#	description = "Lorem ipsum dolor sit amet."



	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "If you want to work with me, you can send email to me. Thanks!"

		# address = []
		# phone = ""

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "schwarzmeifu@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
